/*
DADO UNA CADENA DE TEXTO, COMPROBAR SI ES UN PALINDROMO O NO. LOS PALINDROMOS SON PALABRAS QUE SE LEEN IGUAL AUN ESTANDO INVERTIDA.

POR EJEMPLO : ANA, BOB, OTTO, ...

FUNCION:
PALINDROMO("OTTO")//devuelve TRUE
PALINDROMO("VICTOR")//devuelve FALSE
*/